org: demov
app: leakmited
service: leakmited-backend

provider:
  name: aws
  runtime: python3.9
  region: eu-west-3
  endpointType: REGIONAL
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeAsync
            - lambda:InvokeFunction
            - lambda:GetLayerVersion
            - s3:*
          Resource:
            - arn:aws:lambda:eu-west-3:784039913349:function:*
            - arn:aws:lambda:eu-west-3:784039913349:layer:*
            - arn:aws:s3:::*

custom:
  basePath: "."
  cwdPath: "."
  layerShared: "layers-shared-prod"

package:
  individually: true

functions:
  leakmited_api:
    handler: src/main.handler
    timeout: 30
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_NAME: ${env:DB_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASS: ${env:DB_PASS}
    package:
      exclude:
        - ./**
      include:
        - ${self:custom.basePath}/src/**
    url:
      cors: true
    layers:
      - ${cf:${self:custom.layerShared}.FastoLambdaLayerQualifiedArn}
      - ${cf:${self:custom.layerShared}.SqloLambdaLayerQualifiedArn}
      # - ${cf:${self:custom.layerShared}.TypingLambdaLayerQualifiedArn}
